openapi: 3.0.0
info:
  title: Ecommerce API
  description: Multi Vendor Ecommerce API
  contact: {}
  version: '1.0.0'
servers:
  - url: http://localhost:5000/api/v1
    description: Developpement Server
    variables: {}
  - url: http://localhost:5000/api/v1
    description: Live Server
    variables: {}
paths:
  /auth/register:
    post:
      tags:
        - Auth
      summary: Register User
      operationId: RegisterUser
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterUserRequest'
            example:
              name: bob
              email: bob@gmail.com
              password: secret
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /auth/login:
    post:
      tags:
        - Auth
      summary: Login User
      operationId: LoginUser
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUserRequest'
            example:
              email: susan@gmail.com
              password: secret
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /auth/logout:
    delete:
      tags:
        - Auth
      summary: Logout User
      operationId: LogoutUser
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /auth/forgot_password:
    post:
      tags:
        - Auth
      summary: Forgot Password
      operationId: ForgotPassword
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUserRequest'
            example:
              email: susan@gmail.com
              password: secret
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /auth/verify-email:
    post:
      tags:
        - Auth
      summary: Verify User Email
      operationId: VerifyUserEmail
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUserRequest'
            example:
              email: susan@gmail.com
              password: secret
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /auth/reset-password:
    post:
      tags:
        - Auth
      summary: Reset Password
      operationId: ResetPassword
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUserRequest'
            example:
              email: susan@gmail.com
              password: secret
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /auth/change-password:
    post:
      tags:
        - Auth
      summary: Change Password
      operationId:  ChangePassword
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUserRequest'
            example:
              email: susan@gmail.com
              password: secret
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /categories:
    get:
      tags:
        - Category
      summary: Get all categories
      description: Public endpoint to retrieve all categories with filtering options
      parameters:
        - in: query
          name: search
          schema:
            type: string
        - in: query
          name: sort
          schema:
            type: string
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
        - in: query
          name: select
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  count:
                    type: integer
                  total:
                    type: integer
                  pages:
                    type: integer
                  currentPage:
                    type: integer
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Category'
    
    post:
      tags:
        - Category
      summary: Create a new category
      security:
        - BearerAuth: []
      description: Admin only endpoint to create a new category
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - name
                - description
                - image
              properties:
                name:
                  type: string
                description:
                  type: string
                image:
                  type: string
                  format: binary
      responses:
        '201':
          description: Category created successfully
        '401':
          description: Unauthorized - Not logged in
        '403':
          description: Forbidden - Not admin
        '400':
          description: Bad request

  /categories/{id}:
    tags:
        - Category
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
        description: Category ID
    
    get:
      tags:
        - Category
      summary: Get a single category
      responses:
        '200':
          description: Category found
          content:
            application/json:
              schema:
                type: object
                properties:
                  category:
                    $ref: '#/components/schemas/Category'
        '404':
          description: Category not found

    put:
      tags:
        - Category
      summary: Update a category
      security:
        - BearerAuth: []
      description: Admin only endpoint to update category details
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
      responses:
        '200':
          description: Category updated successfully
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - Not admin
        '404':
          description: Category not found

    delete:
      tags:
        - Category
      summary: Delete a category
      security:
        - BearerAuth: []
      description: Admin only endpoint to delete a category
      responses:
        '200':
          description: Category deleted successfully
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - Not admin
        '404':
          description: Category not found

  /categories/{id}/update-category-image:
    put:
      tags:
        - Category
      summary: Update category image
      security:
        - BearerAuth: []
      description: Admin only endpoint to update category image
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - image
              properties:
                image:
                  type: string
                  format: binary
      responses:
        '200':
          description: Image updated successfully
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - Not admin
        '404':
          description: Category not found

  /categories/{categoryId}/subcategories:
    post:
      tags:
        - Category
      summary: Add a subcategory
      security:
        - BearerAuth: []
      description: Admin only endpoint to add a subcategory
      parameters:
        - in: path
          name: categoryId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - description
              properties:
                name:
                  type: string
                description:
                  type: string
      responses:
        '201':
          description: Subcategory added successfully
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - Not admin
        '404':
          description: Category not found

  /categories/{categoryId}/subcategories/{subcategoryId}:
    tags:
        - Category
    parameters:
      - in: path
        name: categoryId
        required: true
        schema:
          type: string
      - in: path
        name: subcategoryId
        required: true
        schema:
          type: string
    
    put:
      tags:
        - Category
      summary: Update a subcategory
      security:
        - BearerAuth: []
      description: Admin only endpoint to update a subcategory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
      responses:
        '200':
          description: Subcategory updated successfully
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - Not admin
        '404':
          description: Category or subcategory not found

    delete:
      tags:
        - Category
      summary: Delete a subcategory
      security:
        - BearerAuth: []
      description: Admin only endpoint to delete a subcategory
      responses:
        '200':
          description: Subcategory deleted successfully
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - Not admin
        '404':
          description: Category or subcategory not found
  
  
  
  
  /jobs:
    post:
      tags:
        - Jobs
      summary: Create Job
      operationId: CreateJob
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateJobRequest'
            example:
              company: google
              position: front-end developer
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    get:
      tags:
        - Jobs
      summary: Get All Jobs
      operationId: GetAllJobs
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /jobs/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: The job ID
    get:
      tags:
        - Jobs
      summary: Get Single Job
      operationId: GetSingleJob
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false

    patch:
      tags:
        - Jobs
      summary: Update Job
      operationId: UpdateJob
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateJobRequest'
            example:
              company: random
              position: intern
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    delete:
      tags:
        - Jobs
      summary: Delete Job
      operationId: DeleteJob
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
components:
  schemas:
    SubCategory:
      type: object
      required:
        - name
        - description
      properties:
        _id:
          type: string
          format: uuid
          description: Auto-generated subcategory ID
        name:
          type: string
          description: Name of the subcategory
        description:
          type: string
          description: Description of the subcategory
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    Category:
      type: object
      required:
        - name
        - description
        - image
      properties:
        _id:
          type: string
          format: uuid
        name:
          type: string
          description: Unique name of the category
        description:
          type: string
        image:
          type: object
          properties:
            public_id:
              type: string
              description: Cloudinary public ID
            url:
              type: string
              format: uri
              description: Cloudinary secure URL
        subcategories:
          type: array
          items:
            $ref: '#/components/schemas/SubCategory'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    
    RegisterUserRequest:
      title: RegisterUserRequest
      required:
        - name
        - email
        - password
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
      example:
        name: bob
        email: bob@gmail.com
        password: secret
    
    LoginUserRequest:
      title: LoginUserRequest
      required:
        - email
        - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: susan@gmail.com
        password: secret
    
    CreateJobRequest:
      title: CreateJobRequest
      required:
        - company
        - position
      type: object
      properties:
        company:
          type: string
        position:
          type: string
      example:
        company: google
        position: front-end developer
    
    UpdateJobRequest:
      title: UpdateJobRequest
      required:
        - company
        - position
      type: object
      properties:
        company:
          type: string
        position:
          type: string
      example:
        company: random
        position: intern
  securitySchemes:
    httpBearer:
      type: http
      scheme: bearer
security:
  - httpBearer: []
tags:
  - name: Auth
    description: ''
  - name: Cart
    description: ''
  - name: Category
    description: ''
  - name: User
    description: ''
  - name: Discount
    description: ''
  - name: Favourite
    description: ''
  - name: Order
    description: ''
  - name: Product
    description: ''
  - name: Review
    description: ''

