openapi: 3.0.0
info:
  title: Ecommerce API
  description: Multi Vendor Ecommerce API
  contact: {}
  version: '1.0.0'
servers:
  - url: http://localhost:5000/api/v1
    description: Developpement Server
    variables: {}
  - url: http://localhost:5000/api/v1
    description: Live Server
    variables: {}
paths:
  /auth/register:
    post:
      tags:
        - Auth
      summary: Register User
      operationId: RegisterUser
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterUserRequest'
            example:
              name: bob
              email: bob@gmail.com
              password: secret
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /auth/login:
    post:
      tags:
        - Auth
      summary: Login User
      operationId: LoginUser
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUserRequest'
            example:
              email: susan@gmail.com
              password: secret
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /auth/logout:
    delete:
      tags:
        - Auth
      summary: Logout User
      operationId: LogoutUser
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /auth/forgot_password:
    post:
      tags:
        - Auth
      summary: Forgot Password
      operationId: ForgotPassword
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUserRequest'
            example:
              email: susan@gmail.com
              password: secret
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /auth/verify-email:
    post:
      tags:
        - Auth
      summary: Verify User Email
      operationId: VerifyUserEmail
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUserRequest'
            example:
              email: susan@gmail.com
              password: secret
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /auth/reset-password:
    post:
      tags:
        - Auth
      summary: Reset Password
      operationId: ResetPassword
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUserRequest'
            example:
              email: susan@gmail.com
              password: secret
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
  /auth/change-password:
    post:
      tags:
        - Auth
      summary: Change Password
      operationId:  ChangePassword
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUserRequest'
            example:
              email: susan@gmail.com
              password: secret
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []

  /categories:
    get:
      tags:
        - Category
      summary: Get all categories
      description: |
        Retrieves a paginated list of all categories with optional filtering, sorting, and field selection.
        Supports text search across name and description fields.
      parameters:
        - in: query
          name: search
          schema:
            type: string
          description: |
            Search term to filter categories by name or description.
            Uses text index if enabled, otherwise performs regex search.
            Example: "Electronics"
        - in: query
          name: sort
          schema:
            type: string
          description: |
            Comma-separated list of fields to sort by. Use :desc for descending order.
            Example: "name:desc,createdAt"
          example: "name:desc"
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
          description: | 
             Page number for pagination (default: 1)
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            maximum: 50
          description: |
            Number of items per page (default: 10, max: 50)
            example: 10
        - in: query
          name: select
          schema:
            type: string
          description: |
            Comma-separated list of fields to include in the response.
            Example: "name,description,image"
      responses:
        '200':
          description: Successfully retrieved categories
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  count:
                    type: integer
                    description: Number of items in current page
                    example: 10
                  total:
                    type: integer
                    description: Total number of items across all pages
                    example: 45
                  pages:
                    type: integer
                    description: Total number of pages
                    example: 5
                  currentPage:
                    type: integer
                    description: Current page number
                    example: 1
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Category'
        '400':
          description: Bad request - invalid parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "Invalid sort parameter"
    
    post:
      tags:
        - Category
      summary: Create a new category
      security:
        - BearerAuth: []
      description: |
        Admin only endpoint to create a new category.
        Requires multipart/form-data for image upload.
        Image will be uploaded to Cloudinary.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - name
                - description
                - image
              properties:
                name:
                  type: string
                  description: Unique name for the category
                  example: "Electronics"
                description:
                  type: string
                  description: Detailed description of the category
                  example: "Electronic devices and accessories"
                image:
                  type: string
                  format: binary
                  description: | 
                    Category image file (supported formats: jpg, jpeg, png)
      responses:
        '201':
          description: Category created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  category:
                    $ref: '#/components/schemas/Category'
        '400':
          description: |
            Bad request - validation error
            Possible reasons:
            - Missing required fields
            - Category name already exists
            - Invalid image format
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "This category already exists"
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'

  /categories/{categoryId}/subcategories:
    post:
      tags:
        - Category
      summary: Add a subcategory to a category
      security:
        - BearerAuth: []
      description: |
        Admin only endpoint to add a new subcategory to an existing category.
        Subcategory names must be unique within the category.
      parameters:
        - in: path
          name: categoryId
          required: true
          schema:
            type: string
          description: ID of the parent category
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - description
              properties:
                name:
                  type: string
                  example: "Smartphones"
                  description: Unique name for the subcategory within the parent category
                description:
                  type: string
                  example: "Mobile phones and smartphones"
                  description: Detailed description of the subcategory
      responses:
        '201':
          description: Subcategory added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: "Subcategory added successfully"
                  category:
                    $ref: '#/components/schemas/Category'
        '400':
          description: Bad request - validation error
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "This subcategory already exists"
        '404':
          description: Category not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "No category found with id: 123"

 
  /jobs:
    post:
      tags:
        - Jobs
      summary: Create Job
      operationId: CreateJob
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateJobRequest'
            example:
              company: google
              position: front-end developer
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    get:
      tags:
        - Jobs
      summary: Get All Jobs
      operationId: GetAllJobs
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /jobs/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: The job ID
    get:
      tags:
        - Jobs
      summary: Get Single Job
      operationId: GetSingleJob
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false

    patch:
      tags:
        - Jobs
      summary: Update Job
      operationId: UpdateJob
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateJobRequest'
            example:
              company: random
              position: intern
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    delete:
      tags:
        - Jobs
      summary: Delete Job
      operationId: DeleteJob
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
components:
  schemas:
    schemas:
    SubCategory:
      type: object
      required:
        - name
        - description
      properties:
        _id:
          type: string
          example: "507f1f77bcf86cd799439011"
          description: Auto-generated subcategory ID
        name:
          type: string
          example: "Smartphones"
          description: Name of the subcategory (unique within parent category)
        description:
          type: string
          example: "Mobile phones and smartphones"
          description: Detailed description of the subcategory
        createdAt:
          type: string
          format: date-time
          example: "2024-02-02T12:00:00Z"
        updatedAt:
          type: string
          format: date-time
          example: "2024-02-02T12:00:00Z"

    Category:
      type: object
      required:
        - name
        - description
        - image
      properties:
        _id:
          type: string
          example: "507f1f77bcf86cd799439011"
          description: Auto-generated category ID
        name:
          type: string
          example: "Electronics"
          description: Unique name of the category
        description:
          type: string
          example: "Electronic devices and accessories"
          description: Detailed description of the category
        image:
          type: object
          properties:
            public_id:
              type: string
              example: "categories/electronics-123"
              description: Cloudinary public ID for the image
            url:
              type: string
              format: uri
              example: "https://res.cloudinary.com/demo/image/upload/categories/electronics-123.jpg"
              description: Cloudinary secure URL for the image
        subcategories:
          type: array
          description: List of subcategories belonging to this category
          items:
            $ref: '#/components/schemas/SubCategory'
        createdAt:
          type: string
          format: date-time
          example: "2024-02-02T12:00:00Z"
        updatedAt:
          type: string
          format: date-time
          example: "2024-02-02T12:00:00Z"

  responses:
    Unauthorized:
      description: Authentication required
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              error:
                type: string
                example: "Authentication Invalid"

    Forbidden:
      description: User does not have required permissions
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              error:
                type: string
                example: "Not authorized to access this route" 
  
    RegisterUserRequest:
      title: RegisterUserRequest
      required:
        - name
        - email
        - password
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
      example:
        name: bob
        email: bob@gmail.com
        password: secret
    
    LoginUserRequest:
      title: LoginUserRequest
      required:
        - email
        - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: susan@gmail.com
        password: secret
    
    CreateJobRequest:
      title: CreateJobRequest
      required:
        - company
        - position
      type: object
      properties:
        company:
          type: string
        position:
          type: string
      example:
        company: google
        position: front-end developer
    
    UpdateJobRequest:
      title: UpdateJobRequest
      required:
        - company
        - position
      type: object
      properties:
        company:
          type: string
        position:
          type: string
      example:
        company: random
        position: intern
  securitySchemes:
    httpBearer:
      type: http
      scheme: bearer
security:
  - httpBearer: []
tags:
  - name: Auth
    description: ''
  - name: Cart
    description: ''
  - name: Category
    description: ''
  - name: User
    description: ''
  - name: Discount
    description: ''
  - name: Favourite
    description: ''
  - name: Order
    description: ''
  - name: Product
    description: ''
  - name: Review
    description: ''

